### ISSUE TITLE
if you would try to compile it on debian you would..

### ISSUE THREAD

**Issue by noglance** [bcndev/bytecoin#1]
root@server:/var/www/bytecoin2# cmake bytecoin/
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using instrumentation: OFF
-- Using thread sanitizer: OFF
CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106600
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1411 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:85 (find_package)

-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /var/www/bytecoin2

root@server:/var/www/bytecoin2# make
Scanning dependencies of target bytecoin-crypto
[  1%] Building CXX object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto.cpp.o
In file included from /var/www/bytecoin2/bytecoin/src/crypto/crypto.hpp:26:0,
                 from /var/www/bytecoin2/bytecoin/src/crypto/crypto.cpp:26:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::PublicKey::PublicKey()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:34:33: warning: missing initializer for member ‘crypto::EllipticCurvePoint::data’ [-Wmissing-field-initializers]
  PublicKey():EllipticCurvePoint{}{}
                                 ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::SecretKey::SecretKey()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:38:34: warning: missing initializer for member ‘crypto::EllipticCurveScalar::data’ [-Wmissing-field-initializers]
  SecretKey():EllipticCurveScalar{}{}
                                  ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::KeyDerivation::KeyDerivation()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:45:37: warning: missing initializer for member ‘crypto::EllipticCurvePoint::data’ [-Wmissing-field-initializers]
  KeyDerivation():EllipticCurvePoint{}{}
                                     ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::KeyImage::KeyImage()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:49:32: warning: missing initializer for member ‘crypto::EllipticCurvePoint::data’ [-Wmissing-field-initializers]
  KeyImage():EllipticCurvePoint{}{}
                                ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::Signature::Signature()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:54:21: warning: missing initializer for member ‘crypto::EllipticCurveScalar::data’ [-Wmissing-field-initializers]
  Signature():c{}, r{}{}
                     ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:54:21: warning: missing initializer for member ‘crypto::EllipticCurveScalar::data’ [-Wmissing-field-initializers]
[  2%] Building CXX object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-ctx.cpp.o
In file included from /var/www/bytecoin2/bytecoin/src/crypto/hash.hpp:22:0,
                 from /var/www/bytecoin2/bytecoin/src/crypto/hash-ctx.cpp:21:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::PublicKey::PublicKey()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:34:33: warning: missing initializer for member ‘crypto::EllipticCurvePoint::data’ [-Wmissing-field-initializers]
  PublicKey():EllipticCurvePoint{}{}
                                 ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::SecretKey::SecretKey()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:38:34: warning: missing initializer for member ‘crypto::EllipticCurveScalar::data’ [-Wmissing-field-initializers]
  SecretKey():EllipticCurveScalar{}{}
                                  ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::KeyDerivation::KeyDerivation()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:45:37: warning: missing initializer for member ‘crypto::EllipticCurvePoint::data’ [-Wmissing-field-initializers]
  KeyDerivation():EllipticCurvePoint{}{}
                                     ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::KeyImage::KeyImage()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:49:32: warning: missing initializer for member ‘crypto::EllipticCurvePoint::data’ [-Wmissing-field-initializers]
  KeyImage():EllipticCurvePoint{}{}
                                ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp: In constructor ‘crypto::Signature::Signature()’:
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:54:21: warning: missing initializer for member ‘crypto::EllipticCurveScalar::data’ [-Wmissing-field-initializers]
  Signature():c{}, r{}{}
                     ^
/var/www/bytecoin2/bytecoin/src/crypto/types.hpp:54:21: warning: missing initializer for member ‘crypto::EllipticCurveScalar::data’ [-Wmissing-field-initializers]
[  3%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/blake256.c.o
[  4%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/chacha8.c.o
[  5%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto-ops-data.c.o
[  6%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto-ops.c.o
[  7%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto-util.c.o
[  8%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/groestl.c.o
[  9%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-blake.c.o
[ 10%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-groestl.c.o
[ 11%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-jh.c.o
In file included from /var/www/bytecoin2/bytecoin/src/crypto/hash-extra-jh.c:24:0:
/var/www/bytecoin2/bytecoin/src/crypto/hash-impl.h:46:15: error: expected declaration specifiers or ‘...’ before ‘sizeof’
 static_assert(sizeof(union hash_state) == 200, "Invalid structure size");
               ^
/var/www/bytecoin2/bytecoin/src/crypto/hash-impl.h:46:48: error: expected declaration specifiers or ‘...’ before string constant
 static_assert(sizeof(union hash_state) == 200, "Invalid structure size");
                                                ^
CMakeFiles/bytecoin-crypto.dir/build.make:302: recipe for target 'CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-jh.c.o' failed
make[2]: *** [CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-jh.c.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'CMakeFiles/bytecoin-crypto.dir/all' failed
make[1]: *** [CMakeFiles/bytecoin-crypto.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bcndev** [comment]
@noglance thanks for your report.
There two problems you experience while compiling:
* Too new Boost that is not supported by finders of your cmake;
* Too old compiler (gcc 4.9.2) which does not fully respect C++14 used all over across the project. We recommend using gcc 5.4+.
We'll promptly update README to avoid such troubles in the future.

**Comment by noglance** [comment]
gcc was update but boost still the same.

here is output of cmake:

root@server:/var/www/bytecoin2# cmake bytecoin
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using instrumentation: OFF
-- Using thread sanitizer: OFF
CMake Warning at /usr/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.9/Modules/FindBoost.cmake:1539 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:85 (find_package)


-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /var/www/bytecoin2


here is output of make:

root@server:/var/www/bytecoin2# make
Scanning dependencies of target bytecoin-crypto
[  1%] Building CXX object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto.cpp.o
[  2%] Building CXX object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-ctx.cpp.o
[  3%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/blake256.c.o
[  4%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/chacha8.c.o
[  5%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto-ops-data.c.o
[  6%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto-ops.c.o
[  7%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/crypto-util.c.o
[  8%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/groestl.c.o
[  9%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-blake.c.o
[ 10%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-groestl.c.o
[ 11%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-jh.c.o
[ 12%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash-extra-skein.c.o
[ 13%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/hash.c.o
[ 14%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/jh.c.o
[ 15%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/keccak.c.o
[ 17%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/oaes_lib.c.o
[ 18%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/random.c.o
[ 19%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/skein.c.o
[ 20%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/slow-hash_stdc.c.o
[ 21%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/slow-hash_x86.c.o
[ 22%] Building C object CMakeFiles/bytecoin-crypto.dir/src/crypto/tree-hash.c.o
[ 23%] Linking CXX static library bytecoin/libs/libbytecoin-crypto.a
[ 23%] Built target bytecoin-crypto
Scanning dependencies of target bytecoin-core
[ 24%] Building C object CMakeFiles/bytecoin-core.dir/lmdb/libraries/liblmdb/mdb.c.o
[ 25%] Building C object CMakeFiles/bytecoin-core.dir/lmdb/libraries/liblmdb/midl.c.o
[ 26%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/Base58.cpp.o
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp: In function ‘uint64_t common::base58::{anonymous}::uint_8be_to_64(const uint8_t*, size_t)’:
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:87:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    res |= *data++;
    ~~~~^~~~~~~~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:88:3: note: here
   case 2:
   ^~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:90:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    res |= *data++;
    ~~~~^~~~~~~~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:91:3: note: here
   case 3:
   ^~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:93:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    res |= *data++;
    ~~~~^~~~~~~~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:94:3: note: here
   case 4:
   ^~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:96:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    res |= *data++;
    ~~~~^~~~~~~~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:97:3: note: here
   case 5:
   ^~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:99:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    res |= *data++;
    ~~~~^~~~~~~~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:100:3: note: here
   case 6:
   ^~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:102:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    res |= *data++;
    ~~~~^~~~~~~~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:103:3: note: here
   case 7:
   ^~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:105:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
    res |= *data++;
    ~~~~^~~~~~~~~~
/var/www/bytecoin2/bytecoin/src/common/Base58.cpp:106:3: note: here
   case 8:
   ^~~~
[ 27%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/BinaryArray.cpp.o
[ 28%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/CommandLine.cpp.o
[ 29%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/ConsoleTools.cpp.o
[ 30%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/Ipv4Address.cpp.o
[ 31%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/JsonValue.cpp.o
[ 32%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/MemoryStreams.cpp.o
[ 34%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/Streams.cpp.o
[ 35%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/StringTools.cpp.o
[ 36%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/StringView.cpp.o
[ 37%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/Varint.cpp.o
[ 38%] Building CXX object CMakeFiles/bytecoin-core.dir/src/http/Agent.cpp.o
[ 39%] Building CXX object CMakeFiles/bytecoin-core.dir/src/http/JsonRpc.cpp.o
[ 40%] Building CXX object CMakeFiles/bytecoin-core.dir/src/http/RequestParser.cpp.o
[ 41%] Building CXX object CMakeFiles/bytecoin-core.dir/src/http/ResponseParser.cpp.o
[ 42%] Building CXX object CMakeFiles/bytecoin-core.dir/src/http/Server.cpp.o
[ 43%] Building CXX object CMakeFiles/bytecoin-core.dir/src/http/types.cpp.o
[ 44%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/BlockChain.cpp.o
[ 45%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/BlockChainFileFormat.cpp.o
[ 46%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/BlockChainState.cpp.o
[ 47%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Config.cpp.o
[ 48%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/CryptoNoteTools.cpp.o
[ 50%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Currency.cpp.o
[ 51%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Difficulty.cpp.o
[ 52%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Node.cpp.o
[ 53%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/NodeDownloader.cpp.o
[ 54%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/NodeLegacyAPI.cpp.o
[ 55%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/TransactionBuilder.cpp.o
[ 56%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/TransactionExtra.cpp.o
[ 57%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Wallet.cpp.o
[ 58%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletNode.cpp.o
[ 59%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletSerializationV1.cpp.o
[ 60%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletState.cpp.o
[ 61%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletSync.cpp.o
[ 62%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/rpc_api_serialization.cpp.o
[ 63%] Building CXX object CMakeFiles/bytecoin-core.dir/src/seria/BinaryInputStream.cpp.o
[ 64%] Building CXX object CMakeFiles/bytecoin-core.dir/src/seria/BinaryOutputStream.cpp.o
[ 65%] Building CXX object CMakeFiles/bytecoin-core.dir/src/seria/JsonInputStream.cpp.o
[ 67%] Building CXX object CMakeFiles/bytecoin-core.dir/src/seria/JsonInputValue.cpp.o
[ 68%] Building CXX object CMakeFiles/bytecoin-core.dir/src/seria/JsonOutputStream.cpp.o
[ 69%] Building CXX object CMakeFiles/bytecoin-core.dir/src/seria/KVBinaryInputStream.cpp.o
[ 70%] Building CXX object CMakeFiles/bytecoin-core.dir/src/seria/KVBinaryOutputStream.cpp.o
[ 71%] Building CXX object CMakeFiles/bytecoin-core.dir/src/logging/CommonLogger.cpp.o
[ 72%] Building CXX object CMakeFiles/bytecoin-core.dir/src/logging/ConsoleLogger.cpp.o
[ 73%] Building CXX object CMakeFiles/bytecoin-core.dir/src/logging/FileLogger.cpp.o
[ 74%] Building CXX object CMakeFiles/bytecoin-core.dir/src/logging/ILogger.cpp.o
[ 75%] Building CXX object CMakeFiles/bytecoin-core.dir/src/logging/LoggerGroup.cpp.o
[ 76%] Building CXX object CMakeFiles/bytecoin-core.dir/src/logging/LoggerManager.cpp.o
[ 77%] Building CXX object CMakeFiles/bytecoin-core.dir/src/logging/LoggerMessage.cpp.o
[ 78%] Building CXX object CMakeFiles/bytecoin-core.dir/src/platform/DB.cpp.o
[ 79%] Building CXX object CMakeFiles/bytecoin-core.dir/src/platform/ExclusiveLock.cpp.o
[ 80%] Building CXX object CMakeFiles/bytecoin-core.dir/src/platform/Files.cpp.o
[ 81%] Building CXX object CMakeFiles/bytecoin-core.dir/src/platform/Network.cpp.o
[ 82%] Building CXX object CMakeFiles/bytecoin-core.dir/src/platform/PathTools.cpp.o
[ 84%] Building CXX object CMakeFiles/bytecoin-core.dir/src/platform/PreventSleep.cpp.o
[ 85%] Building CXX object CMakeFiles/bytecoin-core.dir/src/p2p/LevinProtocol.cpp.o
[ 86%] Building CXX object CMakeFiles/bytecoin-core.dir/src/p2p/P2P.cpp.o
[ 87%] Building CXX object CMakeFiles/bytecoin-core.dir/src/p2p/P2PClientBasic.cpp.o
[ 88%] Building CXX object CMakeFiles/bytecoin-core.dir/src/p2p/P2pSeria.cpp.o
[ 89%] Building CXX object CMakeFiles/bytecoin-core.dir/src/p2p/PeerDB.cpp.o
[ 90%] Linking CXX static library bytecoin/libs/libbytecoin-core.a
[ 90%] Built target bytecoin-core
Scanning dependencies of target bytecoind
[ 91%] Building CXX object CMakeFiles/bytecoind.dir/src/main_bytecoind.cpp.o
[ 92%] Linking CXX executable bytecoin/bin/bytecoind
/usr/bin/ld: /usr/lib/libboost_system.a(error_code.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/bytecoind.dir/build.make:98: recipe for target 'bytecoin/bin/bytecoind' failed
make[2]: *** [bytecoin/bin/bytecoind] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/bytecoind.dir/all' failed
make[1]: *** [CMakeFiles/bytecoind.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by noglance** [comment]
"You also need Boost 1.58 or newer installed system-wide."

it's necessary to downgrade boost?

current gcc version:

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 7.3.0-1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Debian 7.3.0-1)

**Comment by bcndev** [comment]
@noglance After upgrading toolchain you are almost there. An effective way to build the project is, presumably, to recompile Boost with gcc 7.3 as well and give it a try once again.

**Comment by noglance** [comment]
@bcndev it's compiled fine with new boost and gcc. cool
