### ISSUE TITLE
2FA web wallet 

### ISSUE THREAD

**Issue by Nurlan199206** [bcndev/bytecoin#10]
hey mr.developers, how to disable or restore 2FA from web wallet??? G-authentification codes was lost, writing mails to support@bytecoin.org is useless...

**Comment by bcndev** [comment]
@Nurlan199206 Web wallet is not the project we discuss in here. Please direct such questions to Bytecoin community managers at contact@bytecoin.org.

**Comment by Nurlan199206** [comment]
@bcndev they are ignoring me...

**Comment by FndNur1Labs** [comment]
No I think they busy on improve code
