### ISSUE TITLE
Cant mine on private testnet ?

### ISSUE THREAD

**Issue by quocnhan** [bcndev/bytecoin#101]
1. I tried to create 2 nodes : node1 and node2 --net=test using daemon and these only connect to each other via --exclusive-node-address

- ./bytecoind --net=test --p2p-bind-address=0.0.0.0:8080 --bytecoind-bind-address=0.0.0.0:8081 --data-folder=./nodes/node1 --exclusive-node-address=127.0.0.1:9090 --bytecoind-authorization=zohar:0000

- ./bytecoind --net=test --p2p-bind-address=0.0.0.0:9090 --bytecoind-bind-address=0.0.0.0:9091 --exclusive-node-address=127.0.0.1:8080 --data-folder=./nodes/node2 --bytecoind-authorization=zohar:1111

2. I also use RPC wallet to create addresses on node1

- ./walletd --net=test --bytecoind-remote-address=127.0.0.1:8080 --walletd-bind-address=127.0.0.1:8083 --create-wallet --wallet-file=./wallets/zoharWallet1

- ./walletd --net=test --bytecoind-remote-address=127.0.0.1:8080 --walletd-bind-address=127.0.0.1:8084 --create-wallet --wallet-file=./wallets/zoharWallet2

3. after that i connect to wallet

- ./walletd --net=test --bytecoind-remote-address=127.0.0.1:8080 --walletd-bind-address=127.0.0.1:8083 --wallet-file=./wallets/zoharWallet1

- ./walletd --net=test --bytecoind-remote-address=127.0.0.1:8080 --walletd-bind-address=127.0.0.1:8084 --wallet-file=./wallets/zoharWallet2

My purpose : create private node and test send BCN from address1 to address2 .

Can anyone help me find some solution to mine BCN in node1 and set the address which receives BCN is in wallet1 ? I can't find any rpc daemon to start_mining which similar to Monero :'(

I try to find some external tools like xmrig,xmrstak,minerGate,cpuMiner but i don't know how to config them to mine on my private testnet .

**Comment by bcndev** [comment]
@quocnhan You really need a miner to produce blocks in a testnet. In the recent past, we've released a CPU miner just intended for that and you can now find it in all daemon archives since version 3.4.2.
