### ISSUE TITLE
you cannot send to unlinkable address before amethyst upgrade

### ISSUE THREAD

**Issue by maxya** [bcndev/bytecoin#105]
Trying to move coins from old wallet to new ? 

![image](https://user-images.githubusercontent.com/1087015/56450092-c98ded80-62e7-11e9-978e-8c618e28c3a6.png)

Suggestions ? 
Thanks.

**Comment by pavlowd** [comment]
Hi,
You cannot send to unlinkable address before amethyst upgrade :)
It`s will be possible after hardfork.

**Comment by bcndev** [comment]
Hope this one's gone.
