### ISSUE TITLE
How i can create SecretKeys for generate checkpoints?

### ISSUE THREAD

**Issue by ProofOfRight** [bcndev/bytecoin#107]
Hi devs,

in test_blockchein.cpp i see this code: 
`std::vector<std::string> skeys{"dacb828348483011f63ebb538401b3f3d52e8ce1916278f9b189f820d1ec730e",
		    "3ab19160e48f77b41a9b7f87322542b1e977577f30886db3dce3076806709d0d",
		    "16d4d146d8ba2bbff13a4bb174b4c5d73d3ca22817a6585956a697337be26a09"};`

but i don't understand, from where this strings came. Tell me plz, how i can generate this strings or SecretKeys directly?

Regards!

**Comment by ProofOfRight** [comment]
If someone need it too:

`
void generate_keypair(int count = 10) {
	std::vector <WalletRecord> v_records;

	for (int i = 0; i <= count; i++) {
		WalletRecord record{};
		record.creation_timestamp = platform::now_unix_timestamp();
		random_keypair(record.spend_public_key, record.spend_secret_key);
		v_records.push_back(record);
	}

	std::cout << "S Keys:" << std::endl;
	for (const auto& record : v_records) {
		std::cout << common::to_hex(record.spend_secret_key.as_binary_array()) << std::endl;
	}

	std::cout << "P Keys:" << std::endl;
	for (const auto& record : v_records) {
		std::cout << common::to_hex(record.spend_public_key.as_binary_array()) << std::endl;
	}
}
`

**Comment by ghost** [comment]
Thank you! 😉
