### ISSUE TITLE
How to import blocks.bin to data.mdb ?

### ISSUE THREAD

**Issue by kacipbuah** [bcndev/bytecoin#11]
i download latest blockchain from https://blockchain.bytecoin.org but it is in old format. how can i convert it to new lmdb format?

**Comment by bcndev** [comment]
@kacipbuah Just put `blocks.bin` and `blockindexes.bin` into the data folder and restart `bytecoind`.

**Comment by bcndev** [comment]
We are closing this. If our answer did not help you resolve your problem, please open a new issue.
