### ISSUE TITLE
getTransactions RPC call not returning any transactions

### ISSUE THREAD

**Issue by yasaricli** [bcndev/bytecoin#13]
it's returning an empty transactions arrays

    [{
        "blockHash":"fd2a1a0afa4f75da80c4ab0cc22a692c41197a2fa873daee0cf69897c5182de8",
        "transactions": []
    }]

**Comment by bcndev** [comment]
@yasaricli Could you please expose your curl request to `walletd`?

**Comment by yasaricli** [comment]
@bcndev  there was already such a problem.

    curl -X POST --data '{ "params":{ "blockCount":1000, "firstBlockIndex":1, "addresses" :[ "26VmKLjRiuLYGHtQUPGeUQGGD9Bn11pHUTHXtFthHtZjFoJAx46tsV7H5jHP116x39guyqPHZYq6DN9fNJ1Snb3PLjdEpAC" ] }, "jsonrpc":"2.0", "id":"test", "method": "getTransactions" }' 

https://github.com/amjuarez/bytecoin/issues/72

**Comment by bcndev** [comment]
@yasaricli Your question refers to the old Bytecoin, which will become obsolete in a couple of months. Please consider migrating to the new Bytecoin services.
PS: Consult our [wiki](https://github.com/bcndev/bytecoin/wiki) about new API of `bytecoind` and `walletd`.
