### ISSUE TITLE
how to set the blockchain data dir

### ISSUE THREAD

**Issue by bitcodernull** [bcndev/bytecoin#15]
when i use old bytecoin ,i set the data dir as : 
./bytecoind --config-file /home/work/bcn.conf --data-dir /home/work/bcnnode

how to set it on new bytecoin?

**Comment by bcndev** [comment]
@bitcodernull In the new design of Bytecoin its data directory (folder) is fixed across OSes, i.e. there is a permanent place on each OS where Bytecoin stores all stuff. In the next beta release we'll add a cross-platform way to move voluminous data, such as blockchain database, to a user-defined directory.

**Comment by bcndev** [comment]
@bitcodernull The stable version of `walletd`/`bytecoind` now has command-line parameter `--data-folder` to set (daemon) folder/directory.
