### ISSUE TITLE
Question about genesis

### ISSUE THREAD

**Issue by zhmrab** [bcndev/bytecoin#16]
So in src/currency.cpp I see we have 2 lines for the genesis hex : 
Is there a specific reason for writing it like this ? Just wondering :) 

	// Hard code coinbase tx in genesis block, because through generating tx use
	// random, but genesis should be always
	// the same
	std::string genesis_coinbase_tx_hex =
	    "010a01ff0001ffffffffffff0f029b2e4c0281c0b02e7c53291a94d1d0cbff8883f8024f"   "5142ee494ffbbd08807121013c086a48c15fb637a96991bc6d53caf77068b5ba6eeb3c82357228c49790584a";

**Comment by pmitchev** [comment]
You can use --print-genesis-tx from forknoted. The lines are 2 just for readability I guess

**Comment by zhmrab** [comment]
@pmitchev Ok thanks (and thanks for always answering btw..) 

Can these 3.0 binaries actually sync with Forknote (Bytecoin Core 2.1.2) ? 

I've tried --print-genesis-tx but keep on getting this

//
Starting multicore ring checker using 2/4 cpus
Exception in main() - Genesis block failed to add
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: Genesis block failed to add
Abort trap: 6
//

**Comment by bcndev** [comment]
@zhmrab Bytecoin 3.0 has huge modifications across the whole code base, so forknote needs efforts to adapt their code to the latest changes or stay on version 2.0.
