### ISSUE TITLE
fails to read wallet file

### ISSUE THREAD

**Issue by kiahmed** [bcndev/bytecoin#17]
wallet file is mandatory to run walletd , but where this file is supposed to come from? If I try to create one with the command it gets this error. How am I supposed to get a wallet before running it first time? Docs also densest talk about it :(
./walletd --wallet-file=wallet --wallet-password=1234
Exception in main() - IInputStream reading from empty stream
terminate called after throwing an instance of 'std::runtime_error'
  what():  IInputStream reading from empty stream
Aborted (core dumped)

**Comment by noglance** [comment]
OS? path absolute or relevant?

**Comment by kiahmed** [comment]
ubuntu 16.4, path is in the same directory as it says above, do I have to put absolute path?

**Comment by FndNur1Labs** [comment]
.(coinname) @home right?see if there . bin

**Comment by noglance** [comment]
@kiahmed you can try to use absolute path. I'm using absolute and it looks ok with it. Relative path could work fine if you point them from same dir you are launching the app but it may depend from app to app.

**Comment by FndNur1Labs** [comment]
Is there doc how to compile?I'm confused with new bcn make can't used

**Comment by noglance** [comment]
@FndNur1Labs may be it's time to share bin files + md5 for different OS

**Comment by bcndev** [comment]
@kiahmed This snippet should work better: `./walletd --generate-wallet --wallet-file=wallet --wallet-password=1234`.
PS: `--generate-wallet` is subject to change during CLI stabilization period.
PPS: Avoid using ` --wallet-password=...`.

**Comment by kiahmed** [comment]
I had the wallet file in the same dir right next to the daemon. Don't the error looks like the process can't read empty wallet file?

**Comment by kiahmed** [comment]
well, it worked finally but now get this ..no peers?
00:14:36.455278 I P2P No peers to connect to, will try again after 10 seconds
