### ISSUE TITLE
JSON Api Method not found

### ISSUE THREAD

**Issue by simbargit** [bcndev/bytecoin#18]
When I call the method with CURL (php) I recieve this:

 `{"error":{"code":-32601,"message":"Method not found"},"id":"test","jsonrpc":"2.0"}`

**Comment by noglance** [comment]
what is the method name?

**Comment by simbargit** [comment]
With all methods in this page https://github.com/bcndev/bytecoin/wiki/Bytecoin-Wallet-Service-JSON-RPC-API

**Comment by Mycka06** [comment]
I don't  know



Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : Simone Barioglio <notifications@github.com>
Date : 05/03/2018 07:31 (GMT+01:00)
À : bcndev/bytecoin <bytecoin@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [bcndev/bytecoin] JSON Api Method not found (#18)


With all methods in this page https://github.com/bcndev/bytecoin/wiki/Bytecoin-Wallet-Service-JSON-RPC-API

**Comment by FndNur1Labs** [comment]
well maybe different method

**Comment by bcndev** [comment]
@simbargit Make sure you are working with the Beta Bytecoin services. "Method not found" responses are signs of attempts to connect to an old Bytecoin service with the new API.

**Comment by simbargit** [comment]
I downloaded from the official site the Bytecoin Services (Beta) and the daemon start it with this version: "bytecoind • version 3.0.0-20180219-beta • sync status ". I think this is the beta but the error. 

This is my light script with curl
`<?php 

    $url = 'http://127.0.0.1:8081/json_rpc';
    $fields_string = '{"jsonrpc": "2.0", "id": "test", "method": "get_addresses", "params": {}}';
    $ch = curl_init();
    curl_setopt($ch,CURLOPT_URL, $url);
    curl_setopt($ch,CURLOPT_POST, 1);
    curl_setopt($ch,CURLOPT_POSTFIELDS, $fields_string);
    $result = curl_exec($ch);
    curl_close($ch);
?>`

And I get the method in the wiki of this repository (https://github.com/bcndev/bytecoin/wiki/Bytecoin-Wallet-Service-JSON-RPC-API)

**Comment by bcndev** [comment]
@simbargit Look at the port of the endpoint address. You probably want to use `8070` instead of `8081` to talk to `walletd`.

**Comment by simbargit** [comment]
@bcndev No :( 
`$url = 'http://127.0.0.1:8070/json_rpc';`
and i receive
`Curl error: Failed to connect to 127.0.0.1 port 8070: Connection refused`

**Comment by bcndev** [comment]
@simbargit Are you sure you are really talking to `walletd`? It should not be confused with `bytecoind`, which does not deal with user money (wallet file).

**Comment by simbargit** [comment]
@bcndev I can't start `walletd` because I receive this `ExclusiveLock fail at path...Application Support/bytecoin/bytecoind.lock`

**Comment by simbargit** [comment]
@bcndev My mistake! I launched `bytecoind` and `walletd`. Now, with only walletd it's working. Thank you for the support
