### ISSUE TITLE
Mac Wallet is crashing every 5 minutes.

### ISSUE THREAD

**Issue by hostragon-hosting** [bcndev/bytecoin#21]
Hi.
Bytecoin wallet on Mac is crashing a lot.
Please, is there any plan to make this stable?

**Comment by RocksteadyTC** [comment]
What is the nature of this crash? Can you post any logs?

**Comment by hostragon-hosting** [comment]
Here we go.
Happening almost every 5 -7 minutes and that means synchronization is a no-no.
[byte_crash.txt](https://github.com/bcndev/bytecoin/files/1783299/byte_crash.txt)

**Comment by bcndev** [comment]
@hostragon-hosting Please try our [new software](https://bytecoin.org/downloads), which is known to be far more stable.

**Comment by bcndev** [comment]
Closing this issue as technically contentless.
