### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cash2** [bcndev/bytecoin#22]
Hello, the new code structure for bytecoin looks great.  Are there plans to include more tests for the code?  Currently there are crypto, hash, json, txloop, and Io.h.  Thanks.

**Comment by bcndev** [comment]
@cash2 Thanks for the kind words about the result of our hard work. Yes, we plan to fill the project with a lot of tests.

**Comment by FndNur1Labs** [comment]
Need json test to and compabilty with Travis. I already try docker and run
smoothly.

**Comment by bcndev** [comment]
@FndNur1Labs We are on the way.
