### ISSUE TITLE
rpc doesnt respond

### ISSUE THREAD

**Issue by kiahmed** [bcndev/bytecoin#23]
making the following request to bytecoind ..the port is listening and firewall open, but it hangs never returns anything. Same thing happens when request to walletd on port 8070. Any idea?
curl -X POST http://172.17.0.3:8081/json_rpc -H 'Content-Type: application/json-rpc' -d '{"jsonrpc": "2.0", "id": "1", "method": "get_status", "params":[]'

**Comment by bcndev** [comment]
@kiahmed If you are really sure that the host is reachable and `bytecoind` is on, it's not clear why your node doesn't respond.

**Comment by kiahmed** [comment]
i could telnet to the port from outside ..it is reachable..there are other wallets on that machine they works fine. Could you send me sample curl request that works for you?

**Comment by Mycka06** [comment]
Do toi speak  french?



Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : Bytecoin Developers Team <notifications@github.com>
Date : 07/03/2018 16:52 (GMT+01:00)
À : bcndev/bytecoin <bytecoin@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [bcndev/bytecoin] rpc doesnt respond (#23)


@kiahmed<https://github.com/kiahmed> If you are really sure that the host is reachable and bytecoind is on, it's not clear why your node doesn't respond.

**Comment by Mycka06** [comment]
Do you speak french?



Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : kiahmed <notifications@github.com>
Date : 07/03/2018 17:01 (GMT+01:00)
À : bcndev/bytecoin <bytecoin@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [bcndev/bytecoin] rpc doesnt respond (#23)


i could telnet to the port from outside ..it is reachable..there are other wallets on that machine they works fine. Could you send me sample curl request that works for you?

**Comment by kiahmed** [comment]
no unfortunately

**Comment by kiahmed** [comment]
i am just asking for a sample request that works for you, why I have to speak french for that?

**Comment by RocksteadyTC** [comment]
je parle francais, dit moi dans une autre "Issue" que vous voulez

**Comment by bcndev** [comment]
@kiahmed Your request is malformed, try the following one (with a connection timeout set to 5 seconds to guard against long connecting to non-existing `bytecoind`):
`curl --connect-timeout 5 -X POST http://172.17.0.3:8081/json_rpc -H 'Content-Type: application/json-rpc' -d '{"jsonrpc": "2.0", "id": "1", "method": "get_status", "params": {}}'`

**Comment by kiahmed** [comment]
yup that worked. btw, is there a pruning option i can mention in the config?
