### ISSUE TITLE
Bytecoin GUI - remote connection to the node

### ISSUE THREAD

**Issue by virgeny** [bcndev/bytecoin#25]
why you use walletd (8070) in new (v2.0.0-beta-20180219) bytecoin GUI wallet as remote server connection, but not bytecoind (8081) with starting walletd locally. bytecoind remotely will be most useful, because runnung walletd without wallet container has no sense because impossible. 

I just make public node, and now to connect to it, we need open walletd locally , after - open GUI bytecoin wallet and click - connect to remote daemon , and type local address 127.0.0.1

Thank you for answer, in advance.

**Comment by bcndev** [comment]
@virgeny Remote `bytecoind` available from GUI is at the top of our todo list.

**Comment by Mycka06** [comment]
Do ypu speak french?



Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : Bytecoin Developers Team <notifications@github.com>
Date : 07/03/2018 16:55 (GMT+01:00)
À : bcndev/bytecoin <bytecoin@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [bcndev/bytecoin] Bytecoin GUI - remote connection to the node   (#25)


@virgeny<https://github.com/virgeny> Remote bytecoind available from GUI is at the top of our todo list.

**Comment by bcndev** [comment]
@virgeny Connection to remote node is implemented in the latest GUI release.
