### ISSUE TITLE
wallet container synchronization error

### ISSUE THREAD

**Issue by virgeny** [bcndev/bytecoin#26]
![photo_2018-03-10_18-22-08](https://user-images.githubusercontent.com/5560785/37244322-f6195c78-248f-11e8-8cfd-c763ce01ccf9.jpg)

Server side: bytecoind • version 3.0.0-20180219-beta
Bytecoin GUI version 2.0.0.-beta-20180219

Hi , I have two copies of wallet file container, one on the server and the same on PC
on server side - every time when somebody play a game, new address is generated.
So, on PC , that new address not extracted. I can't see new transactions to this wallet, because it haven't check new addresses.

problem I think - because new addresses are not extracted.

So, It work with old wallet container good. without new transactions.
But , when I download new container with new list of addresses within , I have that error.
Thereby I need re-synchronize that wallet and then it will work.

**Comment by bcndev** [comment]
Please clarify, you write "Thereby I need re-synchronize that wallet and then it will work." - we do not understand what actual steps you took to make it work.
If you stop `walletd` on your machine, then copy wallet file from a server, and then start `walletd`, it rechecks recent part of blockchain and should automatically see new transactions. Though, the whole idea of copying wallet file from a server after generating address(es) is horrendously wrong. You should have transaction processor on the server site.

**Comment by virgeny** [comment]
Hi, thank you for the answer.

> Please clarify, you write "Thereby I need re-synchronize that wallet and then it will work." - we do not understand what actual steps you took to make it work.
I mean remove wallet cache folder, and make synchronization again. In this case, of course, that new file will work great.

> Though, the whole idea of copying wallet file from a server after generating address(es) is horrendously wrong.
Ok, I am understand you, in that words. If look from that side, maybe it`s not bug. :)

But it`s not possible/necessary to get new generated addresses in desktop wallet any time when it will be generated on the server. Or I just need to wait,  and it will be implemented in stable version ?

I will try download cache from the server too, and then open wallet.. 

> You should have transaction processor on the server site.
can you explain please ? or better give me some link to more info? thank you.


Best regards, Pavlo

**Comment by virgeny** [comment]
> You should have transaction processor on the server site.
You mean transaction processor like script which work with json_rpc walletd ? :) Yes, I have, but I am glad to check wallet transactions from own PC, so, now when I am download cache from the server - all work fine. So I think my questions is solved :)
