### ISSUE TITLE
Console error in Win64 beta desktop wallet

### ISSUE THREAD

**Issue by dethwave** [bcndev/bytecoin#30]
Parsing received submit leads to throw/catch what=DB::put failed or nooverwrite key already exists hki/0016AD99/
�[2��Fn���&j�Y]�y^@�����[��=If 

This error is repeated in console and prevents sync with the server.

**Comment by bcndev** [comment]
@dethwave Thanks for your bug report. Could you please remove the `walletd` cache, get the latest Bytecoin release, and check if the problem still exists?
