### ISSUE TITLE
ERROR [WalletSync]

### ISSUE THREAD

**Issue by virgeny** [bcndev/bytecoin#38]
There are problem on latest bytecoind and walletd version from 20.03.2018

I have faucet, when every few minutes people can get free bcn, so there are plenty of transactions.
Once in few days - 3-7 days I got problem.

bytecoind can sync ok for example 1495725/1495725 
but in this time walletd stuck only on top block 14957525, and new transactions don`t creates of course.
and I have error in log:

`ERROR [WalletSync] Saving transaction history failed, proof of sending will not be available for tx=28da84bed2454a8d315e9bb5aa3589f46baf4571b9a0e10c5670b1c3ff249939`

so, I am reboot server in this case. and after reboot alright and work fine.

Question:
Why I got that error ? Because walletd stopping syncing ?
And why it stopping syncing ? How can I resume it automatically without reboot?

Maybe there are my mistake somewhere. I'll glad for your answer and advice. 

Best Regards, Pavlo

**Comment by bcndev** [comment]
@virgeny Thanks for reporting such strange behavior.  Could you answer a couple of questions:
1. Which OS do you use?
2. How do you troubleshoot `walletd` stopping sync?
3. Are you sure about the code consuming our API?

**Comment by virgeny** [comment]
Hi, 

1. Ubuntu 16.04 LTS.
2. Now - 'sudo reboot' but it`s manually temporary solution. Work fine but need automatically.
3. Yes, I am use your API in full compliance. Has writen php lib.

starting walletd daemon with 
`echo | /path/to/walletd --wallet-file=/path/to/walletfile --wallet-password=pwdpwdpwd --bytecoind-bind-address=0.0.0.0:8081`

http://prntscr.com/izr4qq - part of lib
and
`$transaction = $bytecoin->create_transaction($change_address,$transfers); `
`$hash = $transaction['transaction']['hash'];`
`$maketransaction = $bytecoin->send_transaction($transaction['binary_transaction']);`

**Comment by virgeny** [comment]
I am moved from 3.0.0 to 3.0.1 , so if there will be the same problem - I`ll report to you.

**Comment by bcndev** [comment]
Reopen it in case of need.

**Comment by virgeny** [comment]
I has it again, on 3.0.2 , after day of use
http://prntscr.com/j6ije0

**Comment by virgeny** [comment]
all that days from Apr 10 to Apr 17 I has 
`ERROR [WalletSync] Saving transaction history failed, proof of sending will not be available for.....`
errors in log file.
But only today is stuck syncing on walletd. 
bytecoind work great

Yesterday I updated bytecoind and walletd to 3.0.2
