### ISSUE TITLE
Asic Resistance

### ISSUE THREAD

**Issue by FndNur1Labs** [bcndev/bytecoin#44]
any info about updates of Asic Resistance?

**Comment by RocksteadyTC** [comment]
TurtleCoin is an ASIC resistant network based on BCN

**Comment by BrunoMarshall** [comment]
in BCN? No way!!  the decision is already taken and soon BCN will reach the max supply(1-2 years)... Please don´t forget that the BCN big whales wanna rump up the project, for that they decided to embrace Asic. 
If i think about myself "(i´m a CPU and GPU miner)", than it´s a horrible move, but for the BCN project and for the big BCN whales is a very intelligent decision. All the Asic miners moved to BCN after monero blocked it. look what happen to BCN? double the price just in weeks...

**Comment by FndNur1Labs** [comment]
but is gamble can  stop?this our thinks bro. sincee big miner comes. many
posted scam or gamble. i made platform used bcn and monero. but i prefer
security used for bcn. since i trust here. what comes is need people can
enable and disable features~

bcn price up nice work.
