### ISSUE TITLE
Network instability

### ISSUE THREAD

**Issue by ns1000** [bcndev/bytecoin#46]
Unlike the old daemon, the new daemon has trouble staying in sync and even worse, once it is out of sync it is impossible to get it back in sync without using a blockchain backup.

This project desperately needs something like monero's -pop-blocks

**Comment by repo23** [comment]
Seem to be having the same issue here, won't get past block 1524227

**Comment by Crypto2** [comment]
Seem to be having the same issue here, won't get past block 1524227

**Comment by ns1000** [comment]
For example: 

DownloadCell BAN height=1525208 wb=17110a9ff1835af2be7db942019e120cce9a3011bcd2e16f515ef1a475edc2ed
Requesting chain from x.x.x.x:8080 remote height=1525242 our height=1525209
Received chain from x.x.x.x:8080 start_height=1525206 length=37
    truncated chain length=35

Eternal loop on this.

**Comment by bcndev** [comment]
Stability of the network is now re-established.
