### ISSUE TITLE
transaction problem.

### ISSUE THREAD

**Issue by sezaiorak** [bcndev/bytecoin#48]
I sent from polo to binance bcn.But I couldn't get them .

Complete | BCN | 34857.70968753
-- | -- | --
  | 2018-05-08 11:55:40Address: 26cw4SobEkzKf1MFigZrB1NQwUQKWT82LP3VeWFzWypSjdu8G3mDVoKJ6xZd4NfiSyUg9rbERYpZ7NCk5rptBMFE5wnE2KfTxid: e1a2bd3ca75e4e2a41c2a14073461a6d4f5615f0ed0d50b47e1851f52e38808b

**Comment by RocksteadyTC** [comment]
Delete this.
