### ISSUE TITLE
Can someone please explain this?

### ISSUE THREAD

**Issue by Endogen** [bcndev/bytecoin#5]
Just found [this thread](https://bitcointalk.org/index.php?topic=740112.0)

I have to say that it is pretty convincing... Any thoughts on this? Is Bytecoin really a scam? Seems like it is!
- Why was the coin 80% premined?
- Why are the dates in the whitepaper faked?
- Who are actually the core devs?
- Why did the repo move from `amjuarez/bytecoin` to `bcndev/bytecoin`?

Thought about investing but that doesn't sound like a good idea anymore. Don't get me wrong, maybe someone can explain this. I'm open for ideas why this is not a scam.

EDIT: I posted this in the [old repo](https://github.com/amjuarez/bytecoin) before i found that development moved here. So therefore i am posting it here too.

**Comment by bcndev** [comment]
@Endogen There won't be a long story from us. This issue is to be closed as irrelevant.

**Comment by Endogen** [comment]
Well, a short explanation would also do it but i guess i know what to think right now.

**Comment by pmitchev** [comment]
Please do not use github issues with not code issues.

**Comment by FndNur1Labs** [comment]
yeah agree or they will spam  like cryptonote~fuk~
