### ISSUE TITLE
Transaction not visible under get_transaction wallet RPC

### ISSUE THREAD

**Issue by Bilan** [bcndev/bytecoin#51]
Hello,
I have a problem with transaction. When I run _get_transfers_ RPC wallet command I can see transaction but when I next run _get_transaction_ with txid from previous command as parameter, wallet RPC returns transaction with default fields. I have this problem only with one transaction, with other it works. Any ideas?

Regards!

**Comment by CooperLee123** [comment]
have you solved the problem, me too
