### ISSUE TITLE
Stuck Transaction 

### ISSUE THREAD

**Issue by adi90x** [bcndev/bytecoin#55]
Hello,

I have performed a transaction and this transaction seems stuck in the middle of nowhere.

It has a transaction hash, it can be lookup in chainradar or minergate blockchain explorer, however it has not receive any confirmation since 72h !!
Do you have an idea of how to include it in a Block ?

Tx ID : 0d76e0b50f4f641d970f7e383443721c4e8c9b68257c1db7efe7c3422be416b6

Thanks a lot for any information !

**Comment by bcndev** [comment]
@adi90x Sorry, this transaction has not been mined in the canonical chain. It's pointed out at the MinerGate site ('previously mined in orphan block').
