### ISSUE TITLE
Do you plan to create block explorer?

### ISSUE THREAD

**Issue by karpotkin** [bcndev/bytecoin#57]

**Comment by FndNur1Labs** [comment]
will follow up. used another block explorer is good too

On 5/16/18, karpotkin <notifications@github.com> wrote:
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bcndev/bytecoin/issues/57


-- 
Nur1Labs©2013
______________________________
Site Info -> Here <http://nur1labs.com/>

Easy Transaction
MoneyBookers <https://www.moneybookers.com/app/?rid=17274145>
