### ISSUE TITLE
Problems with the compiled exe under windows

### ISSUE THREAD

**Issue by hack3r2k** [bcndev/bytecoin#6]
Hi,

I successfully compiled the latest version under win10 x64. Problem is that the exes crash when i im trying to start them. Im using boost 1.64, vs2017 and latest lmdb repo srcs

For example bytecoind throws and c++ library excepption after

Starting multicore ring checker using 4/8 cpus

===========================================================
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: C:\Users\danie\Desktop\bytecoin-master\bin\Debug\bytecoind.exe

abort() has been called

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
============================================================

Bellow is my compilation log

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Rebuild All started: Project: bytecoin-crypto, Configuration: Debug x64 ------
2>Building Custom Rule C:/Users/danie/Desktop/bytecoin-master/CMakeLists.txt
2>crypto.cpp
2>hash-ctx.cpp
2>Generating Code...
2>blake256.c
2>chacha8.c
2>crypto-ops-data.c
2>crypto-ops.c
2>crypto-util.c
2>groestl.c
2>hash-extra-blake.c
2>hash-extra-groestl.c
2>hash-extra-jh.c
2>hash-extra-skein.c
2>hash.c
2>jh.c
2>keccak.c
2>oaes_lib.c
2>random.c
2>skein.c
2>slow-hash_stdc.c
2>slow-hash_x86.c
2>tree-hash.c
2>Generating Code...
2>slow-hash_stdc.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
2>bytecoin-crypto.vcxproj -> C:\Users\danie\Desktop\bytecoin-master\libs\Debug\bytecoin-crypto.lib
2>Done building project "bytecoin-crypto.vcxproj".
3>------ Rebuild All started: Project: bytecoin-core, Configuration: Debug x64 ------
3>Building Custom Rule C:/Users/danie/Desktop/bytecoin-master/CMakeLists.txt
3>cl : Command line warning D9025: overriding '/W3' with '/w'
3>mdb.c
3>midl.c
3>Generating Code...
3>Base58.cpp
3>BinaryArray.cpp
3>CommandLine.cpp
3>ConsoleTools.cpp
3>Ipv4Address.cpp
3>JsonValue.cpp
3>MemoryStreams.cpp
3>Streams.cpp
3>StringTools.cpp
3>StringView.cpp
3>Varint.cpp
3>BinaryInputStream.cpp
3>BinaryOutputStream.cpp
3>JsonInputStream.cpp
3>JsonInputValue.cpp
3>JsonOutputStream.cpp
3>KVBinaryInputStream.cpp
3>KVBinaryOutputStream.cpp
3>Generating Code...
3>Agent.cpp
3>JsonRpc.cpp
3>RequestParser.cpp
3>ResponseParser.cpp
3>Server.cpp
3>types.cpp
3>BlockChain.cpp
3>BlockChainFileFormat.cpp
3>BlockChainState.cpp
3>Config.cpp
3>CryptoNoteTools.cpp
3>Currency.cpp
3>Difficulty.cpp
3>Node.cpp
3>NodeDownloader.cpp
3>NodeLegacyAPI.cpp
3>TransactionBuilder.cpp
3>TransactionExtra.cpp
3>Wallet.cpp
3>WalletNode.cpp
3>Generating Code...
3>Compiling...
3>WalletSerializationV1.cpp
3>WalletState.cpp
3>WalletSync.cpp
3>rpc_api_serialization.cpp
3>CommonLogger.cpp
3>ConsoleLogger.cpp
3>FileLogger.cpp
3>ILogger.cpp
3>LoggerGroup.cpp
3>LoggerManager.cpp
3>LoggerMessage.cpp
3>DB.cpp
3>ExclusiveLock.cpp
3>Files.cpp
3>Network.cpp
3>PathTools.cpp
3>PreventSleep.cpp
3>LevinProtocol.cpp
3>P2P.cpp
3>P2PClientBasic.cpp
3>Generating Code...
3>Compiling...
3>P2pSeria.cpp
3>PeerDB.cpp
3>Generating Code...
3>bytecoin-core.vcxproj -> C:\Users\danie\Desktop\bytecoin-master\libs\Debug\bytecoin-core.lib
3>Done building project "bytecoin-core.vcxproj".
4>------ Rebuild All started: Project: bytecoind, Configuration: Debug x64 ------
5>------ Rebuild All started: Project: tests, Configuration: Debug x64 ------
6>------ Rebuild All started: Project: walletd, Configuration: Debug x64 ------
4>Building Custom Rule C:/Users/danie/Desktop/bytecoin-master/CMakeLists.txt
5>Building Custom Rule C:/Users/danie/Desktop/bytecoin-master/CMakeLists.txt
6>Building Custom Rule C:/Users/danie/Desktop/bytecoin-master/CMakeLists.txt
5>main_tests.cpp
6>main_walletd.cpp
4>main_bytecoind.cpp
5>test_crypto.cpp
5>test_hash.cpp
5>test_json.cpp
5>Generating Code...
5>tests.vcxproj -> C:\Users\danie\Desktop\bytecoin-master\bin\Debug\tests.exe
4>bytecoind.vcxproj -> C:\Users\danie\Desktop\bytecoin-master\bin\Debug\bytecoind.exe
6>walletd.vcxproj -> C:\Users\danie\Desktop\bytecoin-master\bin\Debug\walletd.exe
7>------ Skipped Rebuild All: Project: ALL_BUILD, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
========== Rebuild All: 6 succeeded, 0 failed, 1 skipped ==========

**Comment by bcndev** [comment]
@hack3r2k Thanks for the crash report. It's hard to say what exactly the issue is in your case. Is it possible for you to go debug using standard VS facilities when OS suggests "Press Retry to debug the application"? It'd very helpful at least to locate a file/line where bad things happen.

**Comment by hack3r2k** [comment]
the exe can run when loaded in the debugger if i skip the exception. I used x64dbg for this. Check teh attached image

![clipboard02](https://user-images.githubusercontent.com/36282727/36380520-3faeac12-158b-11e8-8384-eaa1ab868da9.png)

**Comment by bcndev** [comment]
@hack3r2k We're grateful for your attempts to help us. We are still in a state of confusion what's going on on your site. We suggest doing the following: 
* Could you please erase the blockchain folder in the Bytecoin Data Folder, if any.
* Compile the project in Visual Studio under debug mode and start debugging `bytecoind` in __Visual Studio__.

**Comment by bcndev** [comment]
@hack3r2k ping

**Comment by bcndev** [comment]
Close the issue due to inactivity. Please reopen it when any details come up.
