### ISSUE TITLE
How to export-keys from wallet?

### ISSUE THREAD

**Issue by DinoStray** [bcndev/bytecoin#63]
I try to get private key.
So I run
`walletd --bytecoind-remote-address=127.0.0.1:8081  --bytecoind-authorization=rpc_username:password --export-keys --wallet-file=./BlockinWallet`
Then I got
`You can only export keys from a wallet containing 1 address`
What does it mean?

**Comment by virgeny** [comment]
Hi.
Do you have other generated addresses on this wallet ?
Looks like every address has different keys, that`s why you got this error.
But it`s not exactly. Just my guesses
