### ISSUE TITLE
 No peers to connect to, will try again after 10 seconds

### ISSUE THREAD

**Issue by penuel-leo** [bcndev/bytecoin#66]
Hi, I used command 

> ./bytecoind --testnet --bytecoind-bind-address=0.0.0.0:18081
 
**start my bytecoind, but i got error below:**

`
2018-Jun-04 04:26:37.777150 TRACE [START] ----------------------------------------

2018-Jun-04 04:26:37.777657 TRACE [BlockChainState] redo_block {0} height=0 bid=8a6f1cb7ed7a9db4751d7b283a0482baff20567173dbfae136c9bceb188e51c4

2018-Jun-04 04:26:37.823327 INFO [BlockChainState] BlockChainState::BlockChainState height=0 cumulative_difficulty=1 bid=8a6f1cb7ed7a9db4751d7b283a0482baff20567173dbfae136c9bceb188e51c4

2018-Jun-04 04:26:37.824537 INFO [P2P] No peers to connect to, will try again after 10 seconds

2018-Jun-04 04:26:47.824635 INFO [P2P] No peers to connect to, will try again after 10 seconds
`

**Comment by penuel-leo** [comment]
Who can give some suggestions?

**Comment by bcndev** [comment]
@penuel-leo You are trying to connect to `testnet`, which is not yet ready.
