### ISSUE TITLE
Error compiling on OSX

### ISSUE THREAD

**Issue by zhmrab** [bcndev/bytecoin#7]
[ 71%] Linking CXX static library libs/libbytecoin-core.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [libs/libbytecoin-core.a] Error 1
make[1]: *** [CMakeFiles/bytecoin-core.dir/all] Error 2
make: *** [all] Error 2

**Comment by cryptobender69** [comment]
+1

**Comment by zhmrab** [comment]
Solution > 

$ git clone https://github.com/bcndev/bytecoin.git
$ cd bytecoin
$ mkdir -p build
$ cd build
$ cmake .. -G Xcode

Open generated Xcode project file & build
