### ISSUE TITLE
Serializer doesn't support this type of serialization: Object expected

### ISSUE THREAD

**Issue by ProofOfRight** [bcndev/bytecoin#81]
Hello!

I'm trying to run a new blockchain (on Win 10). When executing the RPC-command "submit_block" I get a response with the error:
`{"error":{"code":-32603,"message":"Serializer doesn't support this type of serialization: Object expected."},"id":"0","jsonrpc":"2.0"}
`
ps. for working with curl i use "MSYS2 MinGW 64-bit" console
ps2. rpc-command:
`curl -s -u ......
..........
  "method": "submit_block",
  "params": ["01008....b000"]
}'`

Thx!

**Comment by sevendoorknobs** [comment]
Params should include a curly braces around your brackets.

**Comment by ProofOfRight** [comment]
`{"error":{"code":-32700,"message":"Parse error"},"jsonrpc":"2.0"}
`

**Comment by ProofOfRight** [comment]
and without "[]" same error

**Comment by rs-blashyrkh** [comment]
Try this:

..."method": "submit_block", "params": {"blocktemplate_blob": "01008....b000"}}'

**Comment by ProofOfRight** [comment]
> Try this:
> ..."method": "submit_block", "params": {"blocktemplate_blob": "01008....b000"}}'

 
Worked! Thx!
