### ISSUE TITLE
Max Block Height same of old blockchain

### ISSUE THREAD

**Issue by UNIPOOL** [bcndev/bytecoin#84]
Hi,

A little issue, not a real problem, remote nodes 3.2.x show the block height of the old chain.

Example:
bytecoind • version 3.2.3 • sync status 1593862/1594493

Problem:
Not very a problem, just the block maturity can't work on website part, the only way for now it's to take the last block found max height and calculate the maturity with his height.

Thank you in advance

**Comment by nilhcraiv** [comment]
How have you solved it?

**Comment by bcndev** [comment]
@nilhcraiv It heals itself when your daemon connects to the updated ones.
