### ISSUE TITLE
v3.3.0 not compiled

### ISSUE THREAD

**Issue by homdx** [bcndev/bytecoin#88]
Hello. Problem with compile v3.3.0:

Sea logs:

https://hub.docker.com/r/homdx/bytecoin/builds/

[ 50%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/BlockChainState.cpp.o
[ 51%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Config.cpp.o
[ 52%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/CryptoNoteTools.cpp.o
[ 53%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Currency.cpp.o
[ 54%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Difficulty.cpp.o
[ 54%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/DifficultyCheck.cpp.o
[ 55%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Multicore.cpp.o
[ 56%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Node.cpp.o
[ 57%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/NodeDownloader.cpp.o
[ 57%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/NodeDownloaderV3.cpp.o
[ 58%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/NodeLegacyAPI.cpp.o
[ 59%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Node_P2PProtocolBytecoin.cpp.o
[ 60%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Node_P2PProtocolBytecoinNew.cpp.o
[ 61%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/TransactionBuilder.cpp.o
[ 61%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/TransactionExtra.cpp.o
[ 62%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Wallet.cpp.o
[ 63%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletNode.cpp.o
[ 64%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletSerializationV1.cpp.o
[ 64%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletState.cpp.o
[ 65%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletStateBasic.cpp.o
[ 66%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/WalletSync.cpp.o
[ 67%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/rpc_api_serialization.cpp.o
[ 68%] Building CXX object CMakeFiles/bytecoin-core.dir/src/CryptoNote.cpp.o
[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:15:6: error: 'CheckPoint' has not been declared
 Hash CheckPoint::get_message_hash() const { return get_object_hash(*this); }
      ^~~~~~~~~~
/app/bytecoin/src/Core/rpc_api_serialization.cpp:15:37: error: non-member function 'crypto::Hash get_message_hash()' cannot have cv-qualifier
 Hash CheckPoint::get_message_hash() const { return get_object_hash(*this); }
                                     ^~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'crypto::Hash get_message_hash()':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:15:69: error: invalid use of 'this' in non-member function
 Hash CheckPoint::get_message_hash() const { return get_object_hash(*this); }
                                                                     ^~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::CoinbaseInput&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:133:75: error: 'struct bytecoin::CoinbaseInput' has no member named 'block_index'
 void ser_members(CoinbaseInput &v, ISeria &s) { seria_kv("block_index", v.block_index, s); }
                                                                           ^~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::KeyOutput&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:140:63: error: 'struct bytecoin::KeyOutput' has no member named 'key'
 void ser_members(KeyOutput &v, ISeria &s) { seria_kv("key", v.key, s); }
                                                               ^~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::TransactionPrefix&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:144:28: error: 'struct bytecoin::TransactionPrefix' has no member named 'unlock_time'
  seria_kv("unlock_time", v.unlock_time, s);
                            ^~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::Transaction&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:190:10: error: no match for call to '(seria::ISeria) (crypto::Signature&)'
     s(sig);
          ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:197:10: error: no match for call to '(seria::ISeria) (crypto::Signature&)'
     s(sig);
          ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::BlockTemplate&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:217:34: error: 'make_parent_block_serializer' was not declared in this scope
   auto parent_block_serializer = make_parent_block_serializer(v, false, false);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:217:34: note: suggested alternative: 'parent_block_serializer'
   auto parent_block_serializer = make_parent_block_serializer(v, false, false);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  parent_block_serializer
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: At global scope:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:244:18: error: variable or field 'ser_members' declared void
 void ser_members(CheckPoint &v, seria::ISeria &s) {
                  ^~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:244:18: error: 'CheckPoint' was not declared in this scope
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:244:30: error: 'v' was not declared in this scope
 void ser_members(CheckPoint &v, seria::ISeria &s) {
                              ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:244:47: error: expected primary-expression before '&' token
 void ser_members(CheckPoint &v, seria::ISeria &s) {
                                               ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:244:48: error: 's' was not declared in this scope
 void ser_members(CheckPoint &v, seria::ISeria &s) {
                                                ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:250:18: error: variable or field 'ser_members' declared void
 void ser_members(SignedCheckPoint &v, seria::ISeria &s) {
                  ^~~~~~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:250:18: error: 'SignedCheckPoint' was not declared in this scope
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:250:36: error: 'v' was not declared in this scope
 void ser_members(SignedCheckPoint &v, seria::ISeria &s) {
                                    ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:250:53: error: expected primary-expression before '&' token
 void ser_members(SignedCheckPoint &v, seria::ISeria &s) {
                                                     ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:250:54: error: 's' was not declared in this scope
 void ser_members(SignedCheckPoint &v, seria::ISeria &s) {
                                                      ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::Output&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:256:29: error: 'struct bytecoin::api::Output' has no member named 'global_index'
  seria_kv("global_index", v.global_index, s);
                             ^~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:258:28: error: 'struct bytecoin::api::Output' has no member named 'unlock_time'
  seria_kv("unlock_time", v.unlock_time, s);
                            ^~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::BlockHeader&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:281:74: error: no matching function for call to 'seria_kv(const char [25], uint64_t&, seria::ISeria&, bool)'
  seria_kv("cumulative_difficulty_hi", v.cumulative_difficulty.hi, s, true);
                                                                          ^
[0m[91mIn file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:105:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, T&, seria::ISeria&)'
 void seria_kv(common::StringView name, T &value, ISeria &s) {
      ^~~~~~~~
[0m[91m/app/bytecoin/src/seria/ISeria.hpp:105:6: note:   template argument deduction/substitution failed:
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:281:74: note:   candidate expects 3 arguments, 4 provided
  seria_kv("cumulative_difficulty_hi", v.cumulative_difficulty.hi, s, true);
                                                                          ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:115:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, boost::optional<T>&, seria::ISeria&)'
 void seria_kv(common::StringView name, boost::optional<T> &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:115:6: note:   template argument deduction/substitution failed:
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:281:74: note:   mismatched types 'boost::optional<T>' and 'uint64_t' {aka 'long unsigned int'}
  seria_kv("cumulative_difficulty_hi", v.cumulative_difficulty.hi, s, true);
                                                                          ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:285:45: error: 'struct bytecoin::api::BlockHeader' has no member named 'transactions_cumulative_size'; did you mean 'transactions_size'?
  seria_kv("transactions_cumulative_size", v.transactions_cumulative_size, s);
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                             transactions_size
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:291:33: error: 'struct bytecoin::api::BlockHeader' has no member named 'total_fee_amount'
  seria_kv("total_fee_amount", v.total_fee_amount, s);
                                 ^~~~~~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::Transaction&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:301:28: error: 'struct bytecoin::api::Transaction' has no member named 'unlock_time'
  seria_kv("unlock_time", v.unlock_time, s);
                            ^~~~~~~~~~~
/app/bytecoin/src/Core/rpc_api_serialization.cpp:314:28: error: 'struct bytecoin::api::Transaction' has no member named 'binary_size'
  seria_kv("binary_size", v.binary_size, s);
                            ^~~~~~~~~~~
/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::Balance&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:322:50: error: no matching function for call to 'seria_kv(const char [13], uint64_t&, seria::ISeria&, bool)'
  seria_kv("spendable_hi", v.spendable.hi, s, true);
                                                  ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:105:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, T&, seria::ISeria&)'
 void seria_kv(common::StringView name, T &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:105:6: note:   template argument deduction/substitution failed:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:322:50: note:   candidate expects 3 arguments, 4 provided
  seria_kv("spendable_hi", v.spendable.hi, s, true);
                                                  ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:115:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, boost::optional<T>&, seria::ISeria&)'
 void seria_kv(common::StringView name, boost::optional<T> &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:115:6: note:   template argument deduction/substitution failed:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:322:50: note:   mismatched types 'boost::optional<T>' and 'uint64_t' {aka 'long unsigned int'}
  seria_kv("spendable_hi", v.spendable.hi, s, true);
                                                  ^
/app/bytecoin/src/Core/rpc_api_serialization.cpp:325:60: error: no matching function for call to 'seria_kv(const char [18], uint64_t&, seria::ISeria&, bool)'
  seria_kv("spendable_dust_hi", v.spendable_dust.hi, s, true);
                                                            ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:105:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, T&, seria::ISeria&)'
 void seria_kv(common::StringView name, T &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:105:6: note:   template argument deduction/substitution failed:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:325:60: note:   candidate expects 3 arguments, 4 provided
  seria_kv("spendable_dust_hi", v.spendable_dust.hi, s, true);
                                                            ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:115:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, boost::optional<T>&, seria::ISeria&)'
 void seria_kv(common::StringView name, boost::optional<T> &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:115:6: note:   template argument deduction/substitution failed:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:325:60: note:   mismatched types 'boost::optional<T>' and 'uint64_t' {aka 'long unsigned int'}
  seria_kv("spendable_dust_hi", v.spendable_dust.hi, s, true);
                                                            ^
/app/bytecoin/src/Core/rpc_api_serialization.cpp:328:74: error: no matching function for call to 'seria_kv(const char [25], uint64_t&, seria::ISeria&, bool)'
  seria_kv("locked_or_unconfirmed_hi", v.locked_or_unconfirmed.hi, s, true);
                                                                          ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:105:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, T&, seria::ISeria&)'
 void seria_kv(common::StringView name, T &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:105:6: note:   template argument deduction/substitution failed:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:328:74: note:   candidate expects 3 arguments, 4 provided
  seria_kv("locked_or_unconfirmed_hi", v.locked_or_unconfirmed.hi, s, true);
                                                                          ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:115:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, boost::optional<T>&, seria::ISeria&)'
 void seria_kv(common::StringView name, boost::optional<T> &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:115:6: note:   template argument deduction/substitution failed:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:328:74: note:   mismatched types 'boost::optional<T>' and 'uint64_t' {aka 'long unsigned int'}
  seria_kv("locked_or_unconfirmed_hi", v.locked_or_unconfirmed.hi, s, true);
                                                                          ^
/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::walletd::GetAddresses::Response&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:338:26: error: 'struct bytecoin::api::walletd::GetAddresses::Response' has no member named 'view_only'
  seria_kv("view_only", v.view_only, s);
                          ^~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::walletd::GetTransfers::Request&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:368:43: error: 'struct bytecoin::api::walletd::GetTransfers::Request' has no member named 'desired_transactions_count'; did you mean 'desired_transaction_count'?
  seria_kv("desired_transactions_count", v.desired_transactions_count, s);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                           desired_transaction_count
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::bytecoind::GetStatus::Response&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:409:65: error: invalid static_cast from type 'bytecoin::api::bytecoind::GetStatus::Response' {aka 'bytecoin::api::walletd::GetStatus::Response'} to type 'bytecoin::api::bytecoind::GetStatus::Request&' {aka 'bytecoin::api::walletd::GetStatus::Request&'}
  ser_members(static_cast<api::bytecoind::GetStatus::Request &>(v), s);
                                                                 ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:413:94: error: no matching function for call to 'seria_kv(const char [35], uint64_t&, seria::ISeria&, bool)'
  seria_kv("top_block_cumulative_difficulty_hi", v.top_block_cumulative_difficulty.hi, s, true);
                                                                                              ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:105:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, T&, seria::ISeria&)'
 void seria_kv(common::StringView name, T &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:105:6: note:   template argument deduction/substitution failed:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:413:94: note:   candidate expects 3 arguments, 4 provided
  seria_kv("top_block_cumulative_difficulty_hi", v.top_block_cumulative_difficulty.hi, s, true);
                                                                                              ^
In file included from /app/bytecoin/src/seria/BinaryOutputStream.hpp:6,
                 from /app/bytecoin/src/Core/CryptoNoteTools.hpp:9,
                 from /app/bytecoin/src/Core/rpc_api_serialization.cpp:4:
/app/bytecoin/src/seria/ISeria.hpp:115:6: note: candidate: 'template<class T> void seria::seria_kv(common::StringView, boost::optional<T>&, seria::ISeria&)'
 void seria_kv(common::StringView name, boost::optional<T> &value, ISeria &s) {
      ^~~~~~~~
/app/bytecoin/src/seria/ISeria.hpp:115:6: note:   template argument deduction/substitution failed:
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:413:94: note:   mismatched types 'boost::optional<T>' and 'uint64_t' {aka 'long unsigned int'}
  seria_kv("top_block_cumulative_difficulty_hi", v.top_block_cumulative_difficulty.hi, s, true);
                                                                                              ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::bytecoind::GetRawBlock::Response&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:424:23: error: 'struct bytecoin::api::bytecoind::GetRawBlock::Response' has no member named 'header'
  seria_kv("header", v.header, s);
                       ^~~~~~
/app/bytecoin/src/Core/rpc_api_serialization.cpp:425:27: error: 'struct bytecoin::api::bytecoind::GetRawBlock::Response' has no member named 'raw_header'
  seria_kv("raw_header", v.raw_header, s);
                           ^~~~~~~~~~
/app/bytecoin/src/Core/rpc_api_serialization.cpp:426:33: error: 'struct bytecoin::api::bytecoind::GetRawBlock::Response' has no member named 'raw_transactions'
  seria_kv("raw_transactions", v.raw_transactions, s);
                                 ^~~~~~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:427:38: error: 'struct bytecoin::api::bytecoind::GetRawBlock::Response' has no member named 'base_transaction_hash'
  seria_kv("base_transaction_hash", v.base_transaction_hash, s);
                                      ^~~~~~~~~~~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:428:31: error: 'struct bytecoin::api::bytecoind::GetRawBlock::Response' has no member named 'global_indices'
  seria_kv("global_indices", v.global_indices, s);
                               ^~~~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:429:41: error: 'struct bytecoin::api::bytecoind::GetRawBlock::Response' has no member named 'transaction_binary_sizes'
  seria_kv("transaction_binary_sizes", v.transaction_binary_sizes, s);
                                         ^~~~~~~~~~~~~~~~~~~~~~~~
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::bytecoind::GetRandomOutputs::Request&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:463:27: error: 'struct bytecoin::api::bytecoind::GetRandomOutputs::Request' has no member named 'outs_count'; did you mean 'output_count'?
  seria_kv("outs_count", v.outs_count, s);
                           ^~~~~~~~~~
                           output_count
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: At global scope:
/app/bytecoin/src/Core/rpc_api_serialization.cpp:475:44: error: variable or field 'ser_members' declared void
 void ser_members(bytecoin::api::bytecoind::CheckSendProof::Request &v, ISeria &s) {
                                            ^~~~~~~~~~~~~~
/app/bytecoin/src/Core/rpc_api_serialization.cpp:475:44: error: 'bytecoin::api::bytecoind::CheckSendProof' has not been declared
/app/bytecoin/src/Core/rpc_api_serialization.cpp:475:69: error: 'v' was not declared in this scope
 void ser_members(bytecoin::api::bytecoind::CheckSendProof::Request &v, ISeria &s) {
                                                                     ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp:475:79: error: expected primary-expression before '&' token
 void ser_members(bytecoin::api::bytecoind::CheckSendProof::Request &v, ISeria &s) {
                                                                               ^
/app/bytecoin/src/Core/rpc_api_serialization.cpp:475:80: error: 's' was not declared in this scope
 void ser_members(bytecoin::api::bytecoind::CheckSendProof::Request &v, ISeria &s) {
                                                                                ^
[0m[91m/app/bytecoin/src/Core/rpc_api_serialization.cpp: In function 'void seria::ser_members(bytecoin::api::bytecoind::SubmitBlock::Response&, seria::ISeria&)':
/app/bytecoin/src/Core/rpc_api_serialization.cpp:540:104: error: 'struct bytecoin::api::bytecoind::SubmitBlock::Response' has no member named 'status'
 void ser_members(bytecoin::api::bytecoind::SubmitBlock::Response &v, ISeria &s) { seria_kv("status", v.status, s); }
                                                                                                        ^~~~~~
[0m[ 68%] Building CXX object CMakeFiles/bytecoin-core.dir/src/rpc_api.cpp.o
[91mmake[2]: *** [CMakeFiles/bytecoin-core.dir/build.make:687: CMakeFiles/bytecoin-core.dir/src/Core/rpc_api_serialization.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[0m[91mmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/bytecoin-core.dir/all] Error 2
[0m[91mmake: *** [Makefile:84: all] Error 2
[0m[91m
real	2m0.455s
user	3m37.008s
sys	0m16.958s
[0mRemoving intermediate container bc3fde31380c
[31m[1mThe command '/bin/sh -c set -ex     && mkdir /app/bytecoin/build     && cd bytecoin/build     && cmake ..     && time make -j4     && cp -v ../bin/* /usr/local/bin     && mkdir /usr/local/bin/wallet_file     && cp -v ../tests/wallet_file/* /usr/local/bin/wallet_file     && dnf remove -y make  gcc-c++ cmake git wget openssl-devel     && dnf install libstdc++ -y     && dnf clean all     && rm -rf /app     && echo '[ SHOW VERSION ]'     && bytecoind -v' returned a non-zero code: 2
[22m[39m[31m[SYSTEM] Error: Failed to build image: r.cfcr.io/homdx/homdx/bytecoin:19ddf0662310432107c149217679d6b0a2e1befe; caused by NonZeroExitCodeError: Container for step title: Building Docker Image, step type: build, operation: Building image failed with exit code: 2[0m

**Comment by thrd92** [comment]
I'm using boost 1.68.0 and building also fails at 36%:
> ...
> [ 29%] Built target bytecoin-crypto
> ...
> Scanning dependencies of target bytecoin-core
> **[ 36%] Building CXX object CMakeFiles/bytecoin-core.dir/src/common/Invariant.cpp.o**
> /mnt/ssd/bcn_devel/bytecoin/src/common/Invariant.cpp: In function ‘void common::invariant_violated(const char*, const char*, int, const string&)’:
> /mnt/ssd/bcn_devel/bytecoin/src/common/Invariant.cpp:12:20: error: aggregate ‘std::stringstream str’ has incomplete type and cannot be defined
>   std::stringstream str;
>                     ^~~
> CMakeFiles/bytecoin-core.dir/build.make:254: recipe for target 'CMakeFiles/bytecoin-core.dir/src/common/Invariant.cpp.o' failed
> make[2]: *** [CMakeFiles/bytecoin-core.dir/src/common/Invariant.cpp.o] Error 1
> CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/bytecoin-core.dir/all' failed
> make[1]: *** [CMakeFiles/bytecoin-core.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> real	0m52.695s
> user	0m48.016s
> sys	0m1.392s

OS Debian 9 amd64
cmake configuration log:

> -- The C compiler identification is GNU 6.3.0
> -- The CXX compiler identification is GNU 6.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Better debug: OFF
> -- Instrumentation usage: OFF
> -- Thread sanitizer usage: OFF
> -- Database selected: SQLite 3. Make sure it is put into ../sqlite/
> -- SSL usage: ON. Make sure openssl headers are in ../openssl/include and static libs are in ../openssl/
> -- Boost_INCLUDE_DIRS: ../boost
> -- Boost_LIBRARIES: /mnt/ssd/bcn_devel/bytecoin/../boost/stage/lib/libboost_system.a
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /mnt/ssd/bcn_devel/bytecoin/build

**Comment by bcndev** [comment]
@homdx Thanks for your report, we'll fix it soon.

**Comment by bcndev** [comment]
Fixed via 083dcc032ead2980ffe4f1d4afcb9be4c0df8980.
