### ISSUE TITLE
ExclusiveLock fail at path=/Users/x/Library/Application Support/bytecoin/bytecoind.lock

### ISSUE THREAD

**Issue by zhmrab** [bcndev/bytecoin#9]
Error with walletd on Mac

ExclusiveLock fail at path=/Users/x/Library/Application Support/bytecoin/bytecoind.lock

Output from daemon is 

04:10:07.071160 I P2P No peers to connect to, will try again after 10 seconds
04:10:07.071357 I P2P No peers to connect to, will try again after 10 seconds
....

**Comment by bcndev** [comment]
@zhmrab
* Error message tells you that there is an other `bytecoind` instance running on the host.
* It's not clear why your daemon can't find peers. Which command-line options do you use to run `bytecoind`?

**Comment by zhmrab** [comment]
@bcndev thanks for getting back to me, 

    ~ I figured so I had to shut down bytecoind in order to open walletd, now its working fine
    ~ Im not sure but this is the output that I get from the daemon, my command is just ./bytecoind
       I also tried to fork it and run it on separate network to test it out and I still get :

04:04:07.852465 I P2P No peers to connect to, will try again after 10 seconds
BlockChain::db_commit started... tip_height=0
BlockChain::db_commit finished...
04:04:17.853946 I P2P No peers to connect to, will try again after 10 seconds
04:04:27.857942 I P2P Connecting to=45.76.228.161:4596
04:04:27.861119 I P2P Connecting to=107.191.63.109:4596
04:04:27.861378 I P2P No peers to connect to, will try again after 10 seconds
P2p COMMAND_HANDSHAKE response version=1 unique_number=7853517815627963602 current_height=0 local_peerlist.size=3
04:04:27.958869 I P2P Connecting to=216.189.173.137:4596
04:04:27.959168 I P2P No peers to connect to, will try again after 10 seconds
04:04:27.959168 I P2P No peers to connect to, will try again after 10 seconds`

Any ideas? 
I will keep on testing and will document findings here if anything

**Comment by bcndev** [comment]
We close the issue, since the titled question about exclusive bytecoind lock is answered. Please open an other issue for the problem of not found peers to connect to.
