### ISSUE TITLE
Attention developers. A very important message for you personally.

### ISSUE THREAD

**Issue by mmskam84** [bcndev/bytecoin#94]
Dear developers! If you want to bring your coin to the world level. We have a very big influence. There are big connections in politics. Please contact us. Our email contact@bytecoin.pro

**Comment by BCN-ultimatum** [comment]
Bytecoin is already on the world level, promotes and enables egalitarianism (not a concentrated influence), and transcends political persuasion. Read more on bytecoin.org:

"Bytecoin is a private, decentralized cryptocurrency with open source code that allows everyone to take part in the Bytecoin network development. Privacy and security come naturally from using Bytecoin. The best solution for those who want to keep their financial privacy.

Instant private transactions are provided all around the world by the Bytecoin Network, they are totally untraceable, and they don’t require any additional fees.

Fiat currencies are assigned to specific territories while Bytecoin is bound to the Internet and therefore is international by default."

![bytecoin-logo](https://user-images.githubusercontent.com/44755467/47969687-6bc35d00-e049-11e8-82ce-97fcf1d79424.png)

**Comment by mmskam84** [comment]
Dear developers, please contact us. We want to connect you with influential people who are very interested in the development of Bytecoin. Send us a letter to our address. We will give you all the information. Bytecoin can become the second bitcoin. Do not lose this chance.
I myself am the official Russian-language manager Bytecoin. I am on the official site. Mark Moskalyuk.
I have all the information that you need, I will give you all the information.

**Comment by tribukhouski** [comment]
Mark Moskalyuk's phone and accounts was hacked!!
