### ISSUE TITLE
Build Issue chrono

### ISSUE THREAD

**Issue by ek1977** [bcndev/bytecoin#97]
I am trying to build bytecoin but am running into the error below.  I am using GCC 7.3.  Any help would be appreciated.

[ 25%] Building CXX object CMakeFiles/bytecoin-core.dir/src/Core/Node.cpp.o
In file included from /bcndev/bytecoin/src/http/Agent.cpp:4:0:
/bcndev/bytecoin/src/http/Agent.hpp:62:7: error: 'chrono' in namespace 'std' does not name a type
  std::chrono::steady_clock::time_point request_start;
       ^~~~~~
/bcndev/bytecoin/src/http/Agent.cpp: In member function 'void http::Agent::set_request(http::Request*)':
/bcndev/bytecoin/src/http/Agent.cpp:138:2: error: 'request_start' was not declared in this scope
  request_start = std::chrono::steady_clock::now();
  ^~~~~~~~~~~~~
/bcndev/bytecoin/src/http/Agent.cpp:138:23: error: 'std::chrono' has not been declared
  request_start = std::chrono::steady_clock::now();
                       ^~~~~~
/bcndev/bytecoin/src/http/Agent.cpp: In member function 'void http::Agent::on_reconnect_timer()':
/bcndev/bytecoin/src/http/Agent.cpp:190:23: error: 'std::chrono' has not been declared
  auto idea_sec = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - request_start);
                       ^~~~~~
/bcndev/bytecoin/src/http/Agent.cpp:190:50: error: 'std::chrono' has not been declared
  auto idea_sec = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - request_start);
                                                  ^~~~~~
/bcndev/bytecoin/src/http/Agent.cpp:190:72: error: 'std::chrono' has not been declared
  auto idea_sec = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - request_start);
                                                                        ^~~~~~
/bcndev/bytecoin/src/http/Agent.cpp:190:102: error: 'request_start' was not declared in this scope
  auto idea_sec = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - request_start);
                                                                                                      ^~~~~~~~~~~~~
CMakeFiles/bytecoin-core.dir/build.make:494: recipe for target 'CMakeFiles/bytecoin-core.dir/src/http/Agent.cpp.o' failed
make[2]: *** [CMakeFiles/bytecoin-core.dir/src/http/Agent.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bytecoin-core.dir/all' failed
make[1]: *** [CMakeFiles/bytecoin-core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bcndev** [comment]
@ek1977 Thanks for report. It's been a while since your report so we recommend you try to build the source code once again and reopen/create an issue if it still fails.
